{{- if .Values.migration.enabled -}}
apiVersion: batch/v1
kind: Job
# {{ $shortname := include "calendare.name" . }}
metadata:
  # Unique name per release to avoid conflicts
  name: {{ include "calendare.fullname" . }}-migration-{{ .Release.Revision }}
  labels:
    {{- include "calendare.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    # Ensures migration runs before other hooks (lower is earlier)
    "helm.sh/hook-weight": "-5"
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      name: {{ include "calendare.fullname" . }}-migration
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: migration-bundle
        image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag | default .Values.image.tag | default .Chart.AppVersion }}"
        command: ["./efbundle"]
        args: ["--verbose"]
        envFrom:
            - secretRef:
                name: {{ .Values.calendare.existingDbmsSecret | default (printf "%s-cluster-app" $shortname) }}
              prefix: Postgresql__
{{- end }}
---