apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "calendare.fullname" . }}-job-reader
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  # Needed to check if the job is "Complete" or "Failed"
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "calendare.fullname" . }}-job-reader-binding
subjects:
- kind: ServiceAccount
  name: {{ include "calendare.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "calendare.fullname" . }}-job-reader
  apiGroup: rbac.authorization.k8s.io