---
{{- if not .Values.webpush.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "calendare.fullname" . }}-vapid
type: Opaque
{{- $webpush := .Values.webpush }}
stringData:
  PUBLICKEY: {{ ($webpush.vapid).public | default "missing" | quote  }}
  PRIVATEKEY: {{ ($webpush.vapid).private | default "missing" | quote }}
{{- end }}
---